# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on: http://lint.travis-ci.org/

dist: xenial
language: cpp

compiler:
  - gcc
  - clang
os:
  - linux
  - osx

env:
  - GLOG=1 BUILD_TYPE=Debug
  - GLOG=1 BUILD_TYPE=RelWithDebInfo
  - GLOG=0 BUILD_TYPE=Debug
  - GLOG=0 BUILD_TYPE=RelWithDebInfo

matrix:
  exclude:
    # GCC fails on recent Travis OSX images.
    # https://github.com/travis-ci/travis-ci/issues/9640
    - compiler: gcc
      os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    packages:
    - clang-8
    - cmake
    - gcc-8
    - g++-8
    - ninja-build
  homebrew:
    packages:
    - cmake
    - gcc@8
    - llvm@8
    - ninja
    update: true

before_install:
# The Travis VM image for Mac already has a link at /usr/local/include/c++,
# causing Homebrew's gcc installation to error out. This was reported to
# Homebrew maintainers at https://github.com/Homebrew/brew/issues/1742 and
# removing the link emerged as a workaround.
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f /usr/local/include/c++ ; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
     export PATH="$(brew --prefix llvm)/bin:$PATH";
  fi

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
- echo ${CC}
- echo ${CXX}
- ${CXX} --version
- cmake --version

before_script:
- mkdir -p build && cd build
- cmake .. -G Ninja -DBERRYDB_USE_GLOG=$GLOG -DCMAKE_BUILD_TYPE=$BUILD_TYPE
- cmake --build .
- cd ..

script:
- build/berrydb_tests
- build/berrydb_bench
