# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on: http://lint.travis-ci.org/

language: cpp
dist: xenial
osx_image: xcode10.2

compiler:
  - gcc
  - clang
os:
  - linux
  - osx

env:
  - GLOG=1 BUILD_TYPE=Debug
  - GLOG=1 BUILD_TYPE=RelWithDebInfo
  - GLOG=0 BUILD_TYPE=Debug
  - GLOG=0 BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8
    packages:
    - clang-8
    - cmake
    - gcc-8
    - g++-8
    - ninja-build
  homebrew:
    packages:
    - cmake
    - gcc@8
    - llvm@8
    - ninja
    update: true

before_install:
# The following Homebrew packages aren't linked by default, and need to be
# prepended to the path explicitly.
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
     export PATH="$(brew --prefix llvm)/bin:$PATH";
  fi

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
- echo ${CC}
- echo ${CXX}
- ${CXX} --version
- cmake --version

before_script:
- mkdir -p build && cd build
- cmake .. -G Ninja -DBERRYDB_USE_GLOG=$GLOG -DCMAKE_BUILD_TYPE=$BUILD_TYPE
- cmake --build .
- cd ..

script:
- build/berrydb_tests
- build/berrydb_bench
